### ISSUE TITLE
CNVnator failed -- it's missing a header file: TFrame.h

### ISSUE THREAD

**Issue by crazyhottommy** [cc2qe/speedseq#28]
Hi,
The HPC staff is installing speedseq for me and she told me that CNVnator can not be installed:
CNVnator failed -- it's missing a header file: TFrame.h

Any ideas?
Thanks,
Ming

**Comment by cc2qe** [comment]
Is the ROOT package installed and have you sourced the ROOT environment?
```
source /pathto/root/bin/thisroot.sh
```

**Comment by crazyhottommy** [comment]
yes, ROOT installed, I am not sure if the staff sourced it or not. He installed the CNVnator from https://github.com/abyzovlab/CNVnator and it seems to work.

Ming

**Comment by crazyhottommy** [comment]
I just read the speedseq paper, it says "a custom-designed parallelized build
of CNVnator that is ∼31-fold faster than the original
algorithm", does the one inside the `src` folder the same as here https://github.com/abyzovlab/CNVnator ?

**Comment by cc2qe** [comment]
It's actually slightly different, although if you have the ROOT package installed, the SpeedSeq version should install in the same manner.

I just googled the TFrame.h file and it appears that it is related to ROOT installation, which may have been already fixed in order for your admin to install the official version of CNVnator: http://seqanswers.com/forums/showthread.php?t=16665
